const uuidv1 = require('uuid/v1');

module.exports = {
    "version": 1,
    "kind": "project",
    "id": "EF.Project." + uuidv1().substring(0,6),
    "category": "F.Application",
    "trDescription": "A custom wizard generated by qtcwizard from E-Fever Limited",
    "trDisplayName": "Example Project",
    "trDisplayCategory": "Application",
    "icon": "",
    "enabled": "%{JS: [ %{Plugins} ].indexOf('QmakeProjectManager') >= 0}",
    "options": [
        {
            "key": "QtQuickVersion",
            "value": "%{JS: %{QtVersion}.qtQuickVersion}"
        },
        {
            "key": "ProFileName",
            "value": "%{JS: Util.fileName('%{ProjectDirectory}/%{ProjectName}', 'pro')}"
        }
    ],
    "pages": [
        {
            "trDisplayName": "Project Location",
            "trShortTitle": "Location",
            "typeId": "Project"
        },
        {
            "trDisplayName": "Project Management",
            "trShortTitle": "Summary",
            "typeId": "Summary"
        }
    ],
    "generators": [
        {
            "typeId": "File",
            "data": [
            ]
        }
    ]
}
